# Site
title: DBeditor
subtitle: 最简洁的Markdown编辑器
description: DBeditor The Best MarkDown Editor
author: Bmy
language: zh-Hans
favicon: /images/logo-ico.ico


indexPage:
 title: 开始写作 | 最简洁的Markdown编辑器
 router: index/index
 indexcss: /index/index.css
 markedscript: https://cdn.bootcss.com/marked/0.3.6/marked.min.js
 highlightscript: http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js
 menulisticons:
   save: /images/save.png
   newfile: /images/xj.png
   help: /images/help.png
   full: /images/full.png
   exit: /images/exit.png
   forwar: /images/qinjing.png
   delete: /images/delete.png
   close: /images/ios-close.png
   file: /images/file.png


welcomePage:
 title: 欢迎 | 最简洁的Markdown编辑器
 logo: ../images/markdown.png
 description: DBeditor The Best MarkDown Editor
 router: welcome/welcome
 welcomecss: /welcome/welcome.css
 ribbonscript: http://okkzzhtds.bkt.clouddn.com/ribbon.min.js
 menulist:
    start: { title: Start, href: /index }
    blog: { title:  Blog, href: http://geekhelp.cn/}
    intr: { title: introduce, href: /introduce}
    help: { title: Help, href: /help}

helpPage:
  title: 帮助 | 最简洁的Markdown编辑器
  router: help/help
  helpcss: /stylesheets/help.css
  problemtitle: 有何指教 ？
  BaseUse:
    - itemtitle: 1：基础使用
    - itemtdec: 首先为了更加专注于文章内容的编写，借鉴Vim风格，本应用没有所谓的菜单操作页面，主要是通过快捷键来操作，具体请看下面的快捷键列表：
    - items: Ctrl + S ：文章写完后，即刻保存。
    - itemh: Ctrl + H ：打开软件的帮助页面。
    - itemq: Ctrl + Q ：退出
    - itemp: Ctrl + P ：新建笔记
    - itemd: Ctrl + D ：清除页面内容
    - itemc: Ctrl + C ：复制
    - itemv: Ctrl + V ：粘贴
    - itemx: Ctrl + X ：剪切
    - itemwait: ....开发中，未完待续
  SaveNote:
    - itemtitle: 2：如何本地保存笔记？
    - itemtdec: 写完笔记后，直接快捷键 Ctrl + S 保存，然后打开应用所在目录的 “Note” 文件夹，你的所有笔记都保存在这里面，同时你可以把自己其他的“*.md”文件放到该文件夹中，程序将会自动读取文件并展示。
  HelpMe:
    - itemtitle: 3：赞助我
    - itemtdec: 写个软件不容易，太苦太累，只是为了满足兴趣所以坚持写，何不打赏一块？
    - itemimg: http://obl1kak28.bkt.clouddn.com/zhifubao.png


# JavaScript cdn外链接
JavaScript:
  jquery : https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js
  bootstrap: https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js
  marked: https://cdn.bootcss.com/marked/0.3.6/marked.min.js
  sweetalert2: https://cdn.bootcss.com/limonte-sweetalert2/6.0.1/sweetalert2.min.js
  jqueryToast: https://cdn.bootcss.com/jquery-toast-plugin/1.3.1/jquery.toast.min.js
  keymage: https://cdnjs.cloudflare.com/ajax/libs/keymage/1.1.3/keymage.min.js
  highlight: http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js

# stylesheets cdn外链接
stylesheets:
   bootstrap : http://okkzzhtds.bkt.clouddn.com/bootstrap.min.css
   sweetalert2: https://cdn.bootcss.com/limonte-sweetalert2/6.0.1/sweetalert2.css
   jqueryToast: https://cdn.bootcss.com/jquery-toast-plugin/1.3.1/jquery.toast.min.css
   highlight: http://cdn.bootcss.com/highlight.js/8.0/styles/monokai_sublime.min.css

